FROM node:16

RUN mkdir /app && chown node:node /app
WORKDIR /app

COPY --chown=node:node package.json package.json
COPY --chown=node:node package-lock.json package-lock.json
COPY --chown=node:node tsconfig.json tsconfig.json
COPY --chown=node:node vite.config.ts vite.config.ts


RUN npm install

COPY --chown=node:node . .

CMD ["npm", "run", "dev"]