version: "3.8"

services:
  client:
    container_name: client-gallery-app-mongo-flask
    restart: always
    image: client-gallery-app-mongo-flask:1.0.0
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - VITE_SERVER_HOST=http://192.168.1.160:5000
    volumes:
      - "./client:/app"
    links:
      - server
    depends_on:
      - server
  server:
    container_name: server-gallery-app-mongo-flask
    restart: always
    image: server-gallery-app-mongo-flask:1.0.0
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - JWT_SECRET_KEY=JWT_SECRET_KEY
    volumes:
      - "./server:/app"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo-gallery-app-mongo-flask
    restart: always
    image: mongo
    ports:
      - 27017:27017
    logging:
      driver: none
    volumes:
      - ./db:/data/db:rw
    